package cS356A1;
/**
 * Interface for Student objects.
 * @author Oscar Nevarez
 * @version 1.0
 *
 */
public interface Student {
	
	/**
	 * This method set the passed in ID to the the ID field of this object.
	 * @param ID the String that is the ID for the Student.
	 */
	public void setID(String ID);
	
	/**
	 * This method returns the string of the attached Student instance.
	 * @return returns this CPPStudents ID
	 */
	public String getID();
	
	/**
	 * This method sets the answers generated by the SimulationDriver to this students answer field.
	 * @param answers a string array that represents the students answers.
	 */
	public void setSubmission(String[] answers);
	
	/**
	 * This method returns the array of this students submissions.
	 * @return returns the string Array of this students submissions.
	 */
	public String[] getSubmissions();
}
